### ISSUE TITLE
Endless recursion in avatars_file_storage_load()

### ISSUE THREAD

**Issue by eelkeblok** [dpi/avatars#28] opened 2016-07-16 18:42 UTC
I ran into an endless recursion in avatars_file_storage_load(), although I am not exactly certain of the circumstances. I'm running Drupal 8.1.0 and Avatar TK 1.0-beta4. The avatar generator stack I am using:
- User preference
- User upload
- Gravatar
- Robohash

The recursion is kicked off because avatars_file_storage_load() calls $avatar_preview_storage->loadByProperties() which eventualy will try and get the file storage again, which calls hook_file_storage_load(). And so on. I can turn this into a pull request (I've put some recursin detection in avatars_file_storage_load(), which indeed solves the problem for me), but I am curious what it is about my circumstances that trigger this. I can't imagine this happens always, because it completely breaks the site (I run into the max nesting level because I run xdebug, but I don't think without it this will work). Is anyone else running into this? Any ideas what it is about my setup that causes this? That way it might be easier to devise a test for this.

**Comment by dpi** [comment] 2016-07-16 18:53
I cant say I've encountered this before. Can I get a full stack trace?

**Comment by dpi** [comment] 2016-07-16 18:57
It would be great to be able to reproduce this so a test can be written.

**Comment by eelkeblok** [comment] 2016-07-16 19:06
FWIW, I just pushed my code: https://github.com/eelkeblok/avatars/commit/761d582290111b2d4c2d97292c0ae0859ccb45b9

I can get you a stack trace from my error log, if that helps.

```

 Fatal error:  Maximum function nesting level of '500' reached, aborting! in Unknown on line 0
 Stack trace:
   1. {main}() /index.php:0
   2. Drupal\\Core\\DrupalKernel->handle() /index.php:19
   3. Stack\\StackedHttpKernel->handle() /core/lib/Drupal/Core/DrupalKernel.php:626
   4. Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle() /vendor/stack/builder/src/Stack/StackedHttpKernel.php:23
   5. Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle() /core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php:50
   6. Drupal\\page_cache\\StackMiddleware\\PageCache->handle() /core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php:47
   7. Drupal\\page_cache\\StackMiddleware\\PageCache->pass() /core/modules/page_cache/src/StackMiddleware/PageCache.php:77
   8. Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle() /core/modules/page_cache/src/StackMiddleware/PageCache.php:98
   9. Drupal\\Core\\StackMiddleware\\Session->handle() /core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php:48
  10. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /core/lib/Drupal/Core/StackMiddleware/Session.php:57
  11. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /vendor/symfony/http-kernel/HttpKernel.php:62
  12. Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch() /vendor/symfony/http-kernel/HttpKernel.php:144
  13. Drupal\\Core\\EventSubscriber\\MainContentViewSubscriber->onViewRenderArray() /core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php:111
  14. Drupal\\Core\\Render\\MainContent\\HtmlRenderer->renderResponse() /core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php:90
  15. Drupal\\Core\\Render\\MainContent\\HtmlRenderer->prepare() /core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php:117
  16. Drupal\\Core\\Render\\Renderer->executeInRenderContext() /core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php:227
  17. Drupal\\Core\\Render\\MainContent\\HtmlRenderer->Drupal\\Core\\Render\\MainContent\\{closure}() /core/lib/Drupal/Core/Render/Renderer.php:572
  18. Drupal\\Core\\Render\\Renderer->render() /core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php:226
  19. Drupal\\Core\\Render\\Renderer->doRender() /core/lib/Drupal/Core/Render/Renderer.php:195
  20. Drupal\\Core\\Theme\\ThemeManager->render() /core/lib/Drupal/Core/Render/Renderer.php:433
  21. twig_render_template() /core/lib/Drupal/Core/Theme/ThemeManager.php:384
  22. Twig_Template->render() /core/themes/engines/twig/twig.engine:64
  23. Twig_Template->display() /vendor/twig/twig/lib/Twig/Template.php:366
  24. Twig_Template->displayWithErrorHandling() /vendor/twig/twig/lib/Twig/Template.php:355
  25. __TwigTemplate_36dd0a24b03a2f39cf47baa5ea45da8638774453ffa6dfa8723e63a2914fa100->doDisplay() /vendor/twig/twig/lib/Twig/Template.php:381
  26. Drupal\\Core\\Template\\TwigExtension->escapeFilter() /data/blokspeed/files/php/twig/86a4d663_node.html.twig_3085c8bf4aca218bd46a785d7fd4fcff44b922ae9d26275f06a2a55c2d1a2b81/184e61ba298b1caeb1741fdd9e793eff49abc46549b009503f838e3d47c84da6.php:104
  27. Drupal\\Core\\Render\\Renderer->render() /core/lib/Drupal/Core/Template/TwigExtension.php:462
  28. Drupal\\Core\\Render\\Renderer->doRender() /core/lib/Drupal/Core/Render/Renderer.php:195
  29. Drupal\\Core\\Render\\Renderer->doRender() /core/lib/Drupal/Core/Render/Renderer.php:446
  30. Drupal\\Core\\Theme\\ThemeManager->render() /core/lib/Drupal/Core/Render/Renderer.php:433
  31. twig_render_template() /core/lib/Drupal/Core/Theme/ThemeManager.php:384
  32. Twig_Template->render() /core/themes/engines/twig/twig.engine:64
  33. Twig_Template->display() /vendor/twig/twig/lib/Twig/Template.php:366
  34. Twig_Template->displayWithErrorHandling() /vendor/twig/twig/lib/Twig/Template.php:355
  35. __TwigTemplate_9ed3bdc3c187be0ea2be7aee560a84a3604daf10a6c6ea46da13bddba1b8e74f->doDisplay() /vendor/twig/twig/lib/Twig/Template.php:381
  36. Drupal\\Core\\Template\\TwigExtension->escapeFilter() /data/blokspeed/files/php/twig/86a4d663_field--comment.html.twig_901c2c2c8a63309959190777b5644f949a57a50340300979b585e22586342192/523289a822e2cbef3fcc76f5e2b7b3c6f647d1ffe5aa2d4e732f9030a9b9bf57.php:69
  37. Drupal\\Core\\Render\\Renderer->render() /core/lib/Drupal/Core/Template/TwigExtension.php:462
  38. Drupal\\Core\\Render\\Renderer->doRender() /core/lib/Drupal/Core/Render/Renderer.php:195
  39. Drupal\\Core\\Render\\Renderer->doRender() /core/lib/Drupal/Core/Render/Renderer.php:446
  40. Drupal\\Core\\Theme\\ThemeManager->render() /core/lib/Drupal/Core/Render/Renderer.php:433
  41. twig_render_template() /core/lib/Drupal/Core/Theme/ThemeManager.php:384
  42. Twig_Template->render() /core/themes/engines/twig/twig.engine:64
  43. Twig_Template->display() /vendor/twig/twig/lib/Twig/Template.php:366
  44. Twig_Template->displayWithErrorHandling() /vendor/twig/twig/lib/Twig/Template.php:355
  45. __TwigTemplate_895b130e404c78fe4c91dcfaa2c4c7daf61a2c219479d2ddc0b8caad547743e2->doDisplay() /vendor/twig/twig/lib/Twig/Template.php:381
  46. Drupal\\Core\\Template\\TwigExtension->escapeFilter() /data/blokspeed/files/php/twig/86a4d663_comment.html.twig_905b82a2d95ddf04359bf047c2a3c24ab301916102e2338082511353282c9aca/c8844aa6e6c55a88e61324db06b87eec63ac73d3cc379878e415232f656d94c8.php:57
  47. Drupal\\Core\\Render\\Renderer->render() /core/lib/Drupal/Core/Template/TwigExtension.php:462
  48. Drupal\\Core\\Render\\Renderer->doRender() /core/lib/Drupal/Core/Render/Renderer.php:195
  49. call_user_func:{/core/lib/Drupal/Core/Render/Renderer.php:379}() /core/lib/Drupal/Core/Render/Renderer.php:379
  50. Drupal\\Core\\Entity\\EntityViewBuilder->build() /core/lib/Drupal/Core/Render/Renderer.php:379
  51. Drupal\\Core\\Entity\\EntityViewBuilder->buildMultiple() /core/lib/Drupal/Core/Entity/EntityViewBuilder.php:203
  52. Drupal\\Core\\Entity\\EntityViewBuilder->buildComponents() /core/lib/Drupal/Core/Entity/EntityViewBuilder.php:246
  53. Drupal\\Core\\Entity\\Entity\\EntityViewDisplay->buildMultiple() /core/lib/Drupal/Core/Entity/EntityViewBuilder.php:303
  54. Drupal\\Core\\Field\\FieldItemList->access() /core/lib/Drupal/Core/Entity/Entity/EntityViewDisplay.php:247
  55. Drupal\\Core\\Entity\\EntityAccessControlHandler->fieldAccess() /core/lib/Drupal/Core/Field/FieldItemList.php:165
  56. Drupal\\Core\\Extension\\ModuleHandler->invoke() /core/lib/Drupal/Core/Entity/EntityAccessControlHandler.php:318
  57. call_user_func_array:{/core/lib/Drupal/Core/Extension/ModuleHandler.php:391}() /core/lib/Drupal/Core/Extension/ModuleHandler.php:391
  58. avatars_entity_field_access() /core/lib/Drupal/Core/Extension/ModuleHandler.php:391
  59. Drupal\\avatars\\AvatarManager->syncAvatar() /modules/contrib/avatars/avatars.module:83
  60. Drupal\\avatars\\AvatarManager->findValidAvatar() /modules/contrib/avatars/src/AvatarManager.php:105
  61. Drupal\\avatars\\AvatarManager->refreshAvatarGenerator() /modules/contrib/avatars/src/AvatarManager.php:121
  62. Drupal\\avatars\\Entity\\AvatarPreview::getAvatarPreview() /modules/contrib/avatars/src/AvatarManager.php:136
  63. Drupal\\Core\\Entity\\EntityStorageBase->loadByProperties() /modules/contrib/avatars/src/Entity/AvatarPreview.php:117
  64. Drupal\\Core\\Entity\\EntityStorageBase->loadMultiple() /core/lib/Drupal/Core/Entity/EntityStorageBase.php:504
  65. Drupal\\Core\\Entity\\Sql\\SqlContentEntityStorage->doLoadMultiple() /core/lib/Drupal/Core/Entity/EntityStorageBase.php:242
  66. Drupal\\Core\\Entity\\ContentEntityStorageBase->invokeStorageLoadHook() /core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php:400
  67. file_entity_entity_storage_load() /core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php:388
  68. Drupal\\Core\\Field\\FieldItemBase->__get() /core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php:608
  69. Drupal\\Core\\TypedData\\DataReferenceBase->getValue() /core/lib/Drupal/Core/Field/FieldItemBase.php:140
  70. Drupal\\Core\\Entity\\Plugin\\DataType\\EntityReference->getTarget() /core/lib/Drupal/Core/TypedData/DataReferenceBase.php:37
  71. entity_load() /core/lib/Drupal/Core/Entity/Plugin/DataType/EntityReference.php:70
  72. Drupal\\Core\\Entity\\EntityStorageBase->load() /core/includes/entity.inc:84
  73. Drupal\\Core\\Entity\\EntityStorageBase->loadMultiple() /core/lib/Drupal/Core/Entity/EntityStorageBase.php:212
  74. Drupal\\Core\\Entity\\Sql\\SqlContentEntityStorage->doLoadMultiple() /core/lib/Drupal/Core/Entity/EntityStorageBase.php:242
  75. Drupal\\Core\\Entity\\ContentEntityStorageBase->invokeStorageLoadHook() /core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php:400
  76. avatars_file_storage_load() /core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php:393
  77. Drupal\\Core\\Entity\\EntityStorageBase->loadByProperties() /modules/contrib/avatars/avatars.module:146
  78. Drupal\\Core\\Entity\\EntityStorageBase->loadMultiple() /core/lib/Drupal/Core/Entity/EntityStorageBase.php:504
  79. Drupal\\Core\\Entity\\Sql\\SqlContentEntityStorage->doLoadMultiple() /core/lib/Drupal/Core/Entity/EntityStorageBase.php:242
  80. Drupal\\Core\\Entity\\ContentEntityStorageBase->invokeStorageLoadHook() /core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php:400
  81. file_entity_entity_storage_load() /core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php:388
  82. Drupal\\Core\\Field\\FieldItemBase->__get() /core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php:608
  83. Drupal\\Core\\TypedData\\DataReferenceBase->getValue() /core/lib/Drupal/Core/Field/FieldItemBase.php:140
  84. Drupal\\Core\\Entity\\Plugin\\DataType\\EntityReference->getTarget() /core/lib/Drupal/Core/TypedData/DataReferenceBase.php:37
  85. entity_load() /core/lib/Drupal/Core/Entity/Plugin/DataType/EntityReference.php:70
  86. Drupal\\Core\\Entity\\EntityStorageBase->load() /core/includes/entity.inc:84
  87. Drupal\\Core\\Entity\\EntityStorageBase->loadMultiple() /core/lib/Drupal/Core/Entity/EntityStorageBase.php:212
  88. Drupal\\Core\\Entity\\Sql\\SqlContentEntityStorage->doLoadMultiple() /core/lib/Drupal/Core/Entity/EntityStorageBase.php:242
  89. Drupal\\Core\\Entity\\ContentEntityStorageBase->invokeStorageLoadHook() /core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php:400
  90. avatars_file_storage_load() /core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php:393
```

... and so on.

**Comment by dpi** [comment] 2016-07-22 22:27
edit: just noticed you're using file_entity module. investigating...

**Comment by dpi** [comment] 2016-07-23 00:40
I'm going to go a different route in fixing the issue. See #31. This will also improve performance because it could potentially lead to less SQL database hits.

**Comment by eelkeblok** [comment] 2016-07-24 08:15
Ah, yes, I do use file_entity, had not realized. If you can solve it in another way that's probably better, having some sort of flagging system to prevent recursion has some code smell, I guess.

**Comment by dpi** [comment] 2016-08-23 10:34
Closing in favor of #31 

Follow that issue for updates

**Closed as completed by dpi** 2016-08-23 10:34 UTC
Labels: defect

**Comment by dpi** [comment] 2016-08-23 10:45
@eelkeblok I'd appreciate if you could follow and provide feedback on whether #31 work, so then I can greenlight a new stable release.
