### ISSUE TITLE
Error on creating a new user

### ISSUE THREAD

**Issue by rroose** [dpi/avatars#34] opened 2016-08-19 09:01 UTC
`The website encountered an unexpected error. Please try again later.

Drupal\Core\Database\InvalidQueryException: Query condition 'avatars_preview.uid IN ()' cannot be empty. in Drupal\Core\Database\Query\Condition->condition() (line 71 of core/lib/Drupal/Core/Database/Query/Condition.php).
Drupal\Core\Database\Query\Select->condition('avatars_preview.uid', Array, 'IN') (Line: 53)
Drupal\Core\Entity\Query\Sql\Condition->compile(Object) (Line: 162)
Drupal\Core\Entity\Query\Sql\Query->compile() (Line: 81)
Drupal\Core\Entity\Query\Sql\Query->execute() (Line: 503)
Drupal\Core\Entity\EntityStorageBase->loadByProperties(Array) (Line: 117)
Drupal\avatars\Entity\AvatarPreview::getAvatarPreview(Object, Object) (Line: 136)
Drupal\avatars\AvatarManager->refreshAvatarGenerator(Object, Object, 0) (Line: 163)
Drupal\avatars\AvatarManager->refreshAllAvatars(Object) (Line: 102)
Drupal\avatars\Plugin\Field\FieldWidget\AvatarGeneratorPreviewWidget->formElement(Object, 0, Array, Array, Object) (Line: 324)
Drupal\Core\Field\WidgetBase->formSingleElement(Object, 0, Array, Array, Object) (Line: 85)
Drupal\Core\Field\WidgetBase->form(Object, Array, Object) (Line: 168)
Drupal\Core\Entity\Entity\EntityFormDisplay->buildForm(Object, Array, Object) (Line: 54)
Drupal\Core\Entity\ContentEntityForm->form(Array, Object, Object) (Line: 270)
Drupal\user\AccountForm->form(Array, Object, Object) (Line: 45)
Drupal\user\RegisterForm->form(Array, Object) (Line: 115)
Drupal\Core\Entity\EntityForm->buildForm(Array, Object)
call_user_func_array(Array, Array) (Line: 512)
Drupal\Core\Form\FormBuilder->retrieveForm('user_register_form', Object) (Line: 271)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 74)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber{closure}() (Line: 574)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber{closure}()
call_user_func_array(Object, Array) (Line: 139)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 62)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 98)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 77)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 628)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)`

These are my settings:

![screenshot-settings-avatar-kit](https://cloud.githubusercontent.com/assets/1978126/17804504/391246ce-65fc-11e6-8f44-be48cdfd9983.png)

**Comment by dpi** [comment] 2016-08-19 09:46
Duplicate of #27 

Try the dev version of the module, let me know if it works for you.

**Comment by dpi** [comment] 2016-08-19 09:48
I will tag a new stable release if it works.

**Comment by dpi** [comment] 2016-08-19 14:04
Posted [beta5](https://www.drupal.org/project/avatars/releases/8.x-1.0-beta5)

**Closed as completed** 2016-08-23 09:58 UTC
Labels: duplicate, invalid
